name: Deploy
on:
  push:
    branches: [master]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        script: 
            cd ~/server
            git pull origin master
            git status
            npm i
            npm run start:dev