name: Deploy
on:
  push:
    branches: [ master ]

  jobs: 
    build: 
      runs-on: amazon-linux-latest
      
      steps:
      - name: Auto deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 
            cd ~/server_core
            git pull origin master
            git status
            npm i
            npm run start:dev