name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Auto deploy
          script: 
            cd ~/server_core
            git pull origin master
            git status
            npm i
            npm run start:dev