name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: self-hosted
      
    steps:
    - name: Checkout the files
        uses: actions/checkout@v2

    - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        - run: cd ~/server_core
        - run: git pull origin master
        - run: git status
        - run: npm i
        - run: npm run build
        - run: pm2 restart server