name: Deploy
on:
  push:
    branches: [master]

  jobs: 
    build: 
      runs-on: amazon-latest
      
      steps:
      - name: Auto deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: 
            cd /var/www/server
            git pull origin master
            git status
            npm i
            npm run start:dev